BMEforum/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
    # path('test/', views.TestPage.as_view(), name='test'),
    # path('thanks', views.ThanksPage.as_view(), name='thanks'),


]

groups/urls.py
# GROUPS URLS.PY
from django.urls import path
from . import views

app_name = 'groups'

urlpatterns=[
    path('', views.ListGroups.as_view(), name='all'),
    path('new/', views.CreateGroup.as_view(), name='create'),
    path('posts/in/<slug>/', views.SingleGroup.as_view(), name='single'),
    path('join/<slug>/', views.JoinGroup.as_view(), name='join'),
    path('leave/<slug>/', views.LeaveGroup.as_view(), name='leave'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
    
]

groups/models.py
from django.db import models
from django.utils.text import slugify
from django.urls import reverse
## GROUPS MODELS.PY FILE
# Create your models here.
import misaka

from django.contrib.auth import get_user_model
User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(allow_unicode=True, unique=True)
    description = models.TextField(blank=True, default='')
    description_html = models.TextField(editable=False, default='', blank=True)
    members = models.ManyToManyField(User, through='GroupMember')

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug':self.slug})

    class Meta:
        ordering = ['name']
    

class GroupMember(models.Model):
    group = models.ForeignKey(Group, related_name='membership', on_delete=models.CASCADE)
    user = models.ForeignKey(User, related_name='user_groups', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group', 'user')

groups/views.py
from django.db import IntegrityError
from django.shortcuts import get_object_or_404, render
from django.contrib import messages
# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin

from django.urls import reverse
from django.views import generic
from django.shortcuts import get_object_or_404
from groups.models import Group, GroupMember


class CreateGroup(LoginRequiredMixin, generic.CreateView):
    fields = ('name', 'description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

class JoinGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        group = get_object_or_404(Group, slug=self.kwargs.get('slug'))

        try:
            GroupMember.objects.create(user=self.request.user, group=group)
        except IntegrityError:
            messages.warning(self.request, 'Warning already a member')
        else:
            messages.success(self.request, 'You are now a member!')
        return super().get(request, *args, **kwargs)

class LeaveGroup(LoginRequiredMixin, generic.RedirectView):
    def get_redirect_url(self, *args, **kwargs):
        return reverse('groups:single', kwargs={'slug':self.kwargs.get('slug')})

    def get(self, request, *args, **kwargs):
        try:
            membership = GroupMember.objects.filter(user=self.request.user,
            group__slug=self.kwargs.get('slug')).get()
        except GroupMember.DoesNotExist:
            messages.warning(self.request, 'Sorry you are not in this group!')
        else:
            membership.delete()
            messages.success(self.request, 'You have left the group!')
        return super().get(request, *args, **kwargs)

groups/templates/groups/group_base.html
{% extends 'base.html' %}

{% block content %}

<div class="container">
    <div class="row">
        {% block pregroup %}{% endblock %}
        {% block group_content %}{% endblock %}
        {% block postgroup %}{% endblock %}
    </div>
</div>

{% endblock %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}
{% block pregroup %}
<div class="col-md-8 container">
    <br>
    <br>
    <h1>{{ group.name }}</h1>

    <div class="content">
        <hr style="border: lightgray solid 3px;">
        {{ group.description_html|safe }}

        <span class=" badge bg-warning"><h4>{{ group.members.count }} members</h4></span>

        {% if user in group.members.all %}
            <a href="{% url 'groups:leave' slug=group.slug %}" class="btn btn-lg btn-outline-warning">Leave</a>
        {% else %}
            <a href="{% url 'groups:join' slug=group.slug %}" class="btn btn-lg btn-outline-warning">Join</a>
        {% endif %}

    </div>

</div>
{% endblock %}

{% block group_content %}
<div class="col-md-8 container">

    <br>
    {% if group.posts.count == 0 %}
        No posts in this group yet!
    {% else %}
        {% for post in group.posts.all %}
            <h4>{{ post.message_html|safe }}</h4>
            <small class="username">
                <a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a>
            </small>

            <small>{{ post.created_at }}</small>
            {% if user.is_authenticated and post.user == user %}
                <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-outline-danger">
                        <small> Delete</small>
                        </a>
            {% endif %}
            <hr>

        {% endfor %}
    {% endif %}
    <br>
</div>
<br>
{% endblock %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}
{% load bootstrap5 %}

{% block group_content %}
<h4>Create a new group!</h4>
<form action="{% url 'groups:create' %}" method="POST" id="groupForm">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-outline-warning btn-large" value="Create">
</form>
{% endblock %}

groups/templates/groups/group_list.html
{% extends 'groups/group_base.html' %}
{% load static %}
<link rel="stylesheet" type="text/css" href="{% static 'BMEforum/css/group_list.css' %}">

{% block pregroup %}

<div class="col-md-4">
    <div class="content">
        <br>
        {% if user.is_authenticated %}
            <a href="{% url 'posts:for_user' username=user.username %}"><h1>@{{ user.username }}</h1></a>
            <h1 style="color: #fadd5a;">Welcome Back!!!</h1>
            <p>Check out the groups or create a new group!</p>
        {% else %}
            <h1>Log in and join us!</h1>
        {% endif %}

    </div>
    {% if user.is_authenticated %}
        <a href="{% url 'groups:create' %}" class="btn btn-outline-warning">Create New Group</a>
    {% endif %}

</div>
{% endblock %}


{% block group_content %}
<div class="col-md-8 list_layout">
    <br>
    <div class="list-group">
        {% for group in object_list %}
            <a class='list-group-item' href="{% url 'groups:single' slug=group.slug %}">
                <h3 class="mb-1">{{ group.name }}</h3>
                <p class="mb-1">{{ group.description_html|safe }}</p>
                <h3 class="badge bg-warning rounded-pill">{{ group.members.count }}</h3>
                    member{{ group.members.count|pluralize }}

                <h3 class="badge bg-warning rounded-pill">{{group.posts.count }}</h3>
                    post{{group.posts.count|pluralize}}

                {% if user in group.members.all %}
                    <h3 class="bi bi-person-check-fill" style="float:right;"></h3>
                {% else %}
                    <h3 class="bi bi-person-x-fill" style="float:right;"></h3>
                {% endif %}
            </a>
        {% endfor %}      
    </div>
</div>
{% endblock %}