BMEforum/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
    # path('test/', views.TestPage.as_view(), name='test'),
    # path('thanks', views.ThanksPage.as_view(), name='thanks'),


]

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from accounts import views

app_name = 'accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.SignUp.as_view(), name='signup'),
]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
    
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>BME Forum</title>
    
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">   

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>

    <!-- Google Fonts-->
    <link rel="preconnect" href="https://fonts.googleapis.com"> 
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin> 
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@300&display=swap" rel="stylesheet">
    <!-- Master CSS-->
    <link rel="stylesheet"  type="text/css" href="{% static 'BMEforum/css/master.css' %}">
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.3/font/bootstrap-icons.css">
</head>
<body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <div class="container-fluid">
          <a class="navbar-brand" href="{% url 'home' %}">BME Forum</a>

          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">

                {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url 'posts:all' %}">New Posts</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'posts:for_user' username=user.username %}">My Post</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'posts:create' %}">Add Post</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'groups:all' %}">Groups</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'groups:create' %}">Create Groups</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a></li>
                {% else %}
                    <li class="nav-item"><a class="nav-link" href="{% url 'groups:all' %}">Groups</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:login' %}">Log In</a></li>
                    <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
                {% endif %}

            </ul>
          </div>
        </div>
      </nav>

      <!-- Messages -->
      {% if messages %}
        {% for message in messages %}
          <div class="container-fluid p-0">
            <div class="alert {{ message.tags }} alert-dismissible infomsg" role="alert" id="message_box">
              <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
              {{ message }}
            </div>
          </div>
        {% endfor %}
      {% endif %}
      <script>
        //close alert after 3 seconds
        window.setTimeout(function() {
        $(".alert").fadeTo(500, 0).slideUp(500, function(){
        $(this).remove();
        });
        }, 3000);
        </script>



    <div class="container textoverflow">
        {%block content%}
        {% endblock %}
    </div>
</body>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js" integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script type="text/javascript" src="{% static 'BMEforum/js/master.js' %}"></script>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}

<link href="//db.onlinewebfonts.com/c/0c724f6aa457310440cf8949c615cbd7?family=Star+Jedi" rel="stylesheet" type="text/css"/>

<h1 class="starwars">Welcome to BME Forum!</h1>
<br>
<h3>This is a website for <strong style="color: #fadd5a;">Biomedical Engineers</strong> sharing their protocals.</h3>
<h3>Please sign up first to create a new group or join a group and start sharing your experience! </h3>
{% endblock %}