BMEforum/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(), name='home'),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('posts/', include('posts.urls', namespace='posts')),
    path('groups/', include('groups.urls', namespace='groups')),
    # path('test/', views.TestPage.as_view(), name='test'),
    # path('thanks', views.ThanksPage.as_view(), name='thanks'),


]

posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.PostList.as_view(), name='all'),
    path('new/', views.CreatePost.as_view(), name='create'),
    path('by/<username>/', views.UserPosts.as_view(), name='for_user'),
    path('by/<username>/<int:pk>/', views.PostDetail.as_view(), name='single'),
    path('delete/<int:pk>/', views.DeletePost.as_view(), name='delete'),
    
]

posts/models.py
from django.db import models
from django.urls import reverse
from django.conf import settings
import misaka

from groups.models import Group


## POSTS MODELS.PY
# Create your models here.

from django.contrib.auth import get_user_model
User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts', on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group, related_name='posts', null=True, blank=True, on_delete=models.CASCADE)

    def __str__(self):
        return self.message

    def save(self, *args, **kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('posts:single', 
                        kwargs={'username':self.user.username,
                                'pk':self.pk})

    class Meat:
        ordering = ['-created_at']
        unique_together = ['user', 'message']

posts/views.py
## POSTS VIEWS.PY
# Create your views here.
from django import forms
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.urls import reverse_lazy

from django.http import Http404
from django.views import generic

from braces.views import SelectRelatedMixin

from . import models
from groups.models import Group

from django.contrib.auth import get_user_model
User = get_user_model()

class PostList(SelectRelatedMixin, generic.ListView):
    model = models.Post
    select_related = ('user', 'group')
    queryset=models.Post.objects.all()
 
    def get_context_data(self, **kwargs):
        context = super(PostList, self).get_context_data(**kwargs)
        context['user_groups'] = Group.objects.filter(members__in=[self.request.user])
        context['all_groups'] = Group.objects.all()
        return context

class UserPosts(generic.ListView):
    model = models.Post
    template_name = 'posts/user_post_list.html'

    def get_queryset(self):
        try:
            self.post_user = User.objects.prefetch_related('posts').get(username__iexact=self.kwargs.get('username'))
        except User.DoesNotExist:
            raise Http404
        else:
            return self.post_user.posts.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['post_user'] = self.post_user
        return context

class PostDetail(SelectRelatedMixin, generic.DetailView):
    model = models.Post
    select_related = ('user', 'group')

    def get_queryset(self):
        queryset = super().get_queryset()
        return queryset.filter(user__username__iexact=self.kwargs.get('username'))

class CreatePost(LoginRequiredMixin, SelectRelatedMixin, generic.CreateView):
    fields = ('group', 'message')
    model = models.Post

    def form_valid(self, form):
        self.object = form.save(commit=False)
        self.object.user = self.request.user
        self.object.save()
        return super().form_valid(form)

class DeletePost(LoginRequiredMixin, SelectRelatedMixin, generic.DeleteView):
    model = models.Post
    select_related = ('user', 'group')
    success_url = reverse_lazy('posts:all')

    def get_quertset(self):
        queryset = super().get_queryset()
        return queryset.filter(user_id=self.request.user.id)

    def delete(self, *args, **kwargs):
        messages.success(self.request, 'Post Deleted')
        return super().delete(*args, **kwargs)

posts/templates/posts/_post.html
<h1></h1>

<h4>{{ post.message_html|safe }}</h4>
<p>in Group: <a href="{% url 'groups:single' slug=post.group.slug %}">{{post.group|safe}}</a></p>


<small class="username">
    <a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a>
</small>

<small class="time">
    <a>{{ post.created_at }}</a>

</small>

{% if user.is_authenticated and post.user == user %}
    <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-outline-danger">
        <small> Delete</small>
    </a>
{% endif %}
<hr>

posts/templates/posts/post_base.html
{% extends 'base.html' %}
{% block content %}
<div class="posts-page">
    <div class="container">
        <div class="row">
            {% block prepost %}{% endblock %}
            {% block post_content %}{% endblock %}
            {% block post_post %}{% endblock %}
        </div>
    </div>
</div>
{% endblock %}

posts/templates/posts/post_confirm_delete.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
<h1></h1>
<h1></h1>
<h4 style="color:red;">Are you sure you want to delete this post?</h3>

<h4>{{ post.message_html|safe }}</h4>
<p>in Group: <a href="{% url 'groups:single' slug=post.group.slug %}">{{post.group|safe}}</a></p>

<small class="time">
    <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a>
</small>
<br>
<hr>
<form method="POST">
    {% csrf_token %}
    <input type="submit" value="Delete" class="btn btn-outline-danger">

    <a href="{% url 'posts:single' username=user.username pk=object.pk %}" class="btn btn-outline-warning">Cancel</a>
</form>
{% endblock %}



<div class="posts">
    {% include 'posts/_post.html' with post=object hide_delete=True %}
</div>

<br>
<h4>{{ post.message_html|safe }}</h4>
        <small class="username">
            <a href="{% url 'posts:for_user' username=post.user.username %}">@{{ post.user.username }}</a>
        </small>

        <small class="time">
            <a href="{% url 'posts:single' username=post.user.username pk=post.pk %}">{{ post.created_at }}</a>

        </small>


        {% if user.is_authenticated and post.user == user %}
            <a href="{% url 'posts:delete' pk=post.pk %}" title="delete" class="btn btn-outline-danger">
                <small class="bi bi-x-lg" aria-hidden="true"> Delete</small>
            </a>
        {% endif %}
    <hr>

posts/templates/posts/post_detail.html
{% extends 'posts/post_base.html' %}
{% block post_content %}
<h1></h1>
<h1></h1>
<div class="col-md-8">
    {% include 'posts/_post.html' %}
</div>

{% endblock %}

posts/templates/posts/post_form.html
{% extends 'posts/post_base.html' %}
{% load bootstrap5 %}


{% block post_content %}
<h4>Create a new Post</h4>
<form id="postForm" action="{% url 'posts:create' %}" method="POST">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input type="submit" class="btn btn-outline-warning btn-large" value="Post">

</form>

{% endblock %}

posts/templates/posts/post_list.html
{% extends 'posts/post_base.html' %}
{% load bootstrap5 %}


{% block prepost %}
<div class="col-md-4">
    <br>
    <a href="{% url 'posts:for_user' username=user.username %}"><h1>@{{ user.username }}</h1></a>
    <h1 style="color: #fadd5a;">Welcome Back!!!</h1> 
    {% if request.user.is_authenticated %}
        <h3 class="title">Your Groups</h3>
        <div class="list-group">
            {% for user_group in user_groups %}
                <a class="list-group-item" href="{% url 'groups:single' slug=user_group.slug %}">{{ user_group.slug }}</a>
            {% empty %}
                <h5>no</h5>  
            {% endfor %}
        </div>
    {% endif %}
    <br>
</div>

{% endblock %}

{% block post_content %}
<div class="col-md-8">
    <h1></h1>
    <h3>Check out new posts!</h3>
    {% for post in post_list %}
        {% include 'posts/_post.html' %}
    {% endfor %}
</div>
{% endblock %}

posts/templates/posts/user_post_list.html
{% extends 'posts/post_base.html' %}


{% block prepost %}
<div class="col-md-8 container">
    <br>
    <h1><a href="">@{{ post_user.username }}</a>'s Post History</h1>
    <h1>{{post_user.name}}</h1>

    <br>
    <br>
    {% for post in post_list %}
        {% include 'posts/_post.html' %}
    {% empty %}
    <br>
    <h3>You did not post anything.</h3>
    {% endfor %}
</div>
{% endblock %}